version: '3'

services:
  frontend:
    build:
      context: ./frontend-vite-vanilla/
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend-node-fastify-modular/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"